server:
  port: "8080"
  host: "0.0.0.0"
  vaultsFilePath: "vaults"

redis:
  host: "localhost"
  port: "6379"
  password: ""

relay:
  server: "http://localhost:8080/router"
email_server:
  api_key: "key-1234567890"