plugin:
  type: "payroll"

server:
  mode: "pluginserver"
  port: "8081"
  host: "0.0.0.0"
  vaults_file_path: "vaults"

relay:
  server: "http://localhost:8080/router"

redis:
  host: "localhost"
  port: "6379"
  password: ""

database:
  dsn: "postgres://myuser:mypassword@localhost:5432/mydatabase?sslmode=disable"

block_storage:
  host: "http://localhost:9000"
  region: "us-east-1"
  access_key: "minioadmin"
  secret: "minioadmin"
  bucket: "local/vultiplugin"

email_server:
  api_key: "key-1234567890"
