# vultiserver
server:
  port: "8080"
  host: "localhost"
  vaults_file_path: "/tmp/vultisigner/server/vaults"
  database:
    dsn: "postgres://myuser:mypassword@localhost:5432/vs-plugins-vultiserver?sslmode=disable"

relay:
  server: "https://api.vultisig.com/router"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: "0"

block_storage:
  type: "s3"
  endpoint: "http://localhost:9000"
  bucket: "vultiserver"  
  access_key: "minioadmin"
  secret: "minioadmin"
  region: "us-east-1"
  host: "http://localhost:9000"
  force_path_style: true
  disable_ssl: true

email_server:
  api_key: "key-1234567890"

datadog:
  host: "localhost"
  port: "8125"