server:
  port: "8080"
  host: "0.0.0.0"
  vaults_file_path: "vaults"

redis:
  host: "localhost"
  port: "6379"
  password: ""

relay:
  server: "https://api.vultisig.com/router"
email_server:
  api_key: "9af8c5a82b4cce5ca141be3aa3c3bf01-777a617d-dd16e74b"
