# pluginserver
plugin:
   type: "payroll"
server:
  port: "8081"
  host: "localhost"
  vaults_file_path: "/tmp/vultisigner/plugin/vaults"
  mode: "pluginserver"
  database:
    dsn: "postgres://myuser:mypassword@localhost:5432/vs-plugins-plugin?sslmode=disable"

relay:
  server: "https://api.vultisig.com/router"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: "1"

block_storage:
  type: "s3"
  endpoint: "http://localhost:9000"
  bucket: "vultiplugin" 
  access_key: "minioadmin"
  secret: "minioadmin"
  region: "us-east-1"
  host: "http://localhost:9000"
  force_path_style: true
  disable_ssl: true

email_server:
  api_key: "key-1234567890"

datadog:
  host: "localhost"
  port: "8125"