server:
  port: "8080"
  host: "0.0.0.0"
  vaultsFilePath: "vaults"

redis:
  host: "localhost"
  port: "6379"
  password: ""

encryption:
  privatekey: "test"

relay:
  server: "https://api.vultisig.com/router"
