server:
  port: "8181"
  host: "0.0.0.0"
  vaultsFilePath: "vaults"

redis:
  host: "localhost"
  port: "6379"
  password: ""

encryption:
  privatekey: "test"

relay:
  server: "http://localhost:8080/router"
