services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: signer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  asynqmon:
    platform: linux/amd64
    image: hibiken/asynqmon:latest
    container_name: asynq-monitor
    ports:
      - "8181:8080"
    depends_on:
      - redis

  minio:
    # image: minio/minio
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: signer-minio
    ports:
      - "9000:9000" # s3 api
      - "9090:9090" # console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  redis_data:
  minio_data: 
