services:
  redis:
    image: redis:latest
    container_name: signer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: signer-asynqmon
    ports:
      - "${ASYNQMON_PORT:-8020}:8080"
    environment:
      REDIS_URL: redis://signer-redis:6379/0

volumes:
  # s3_data:
  redis_data:
