services:
  redis:
    image: redis:latest
    container_name: signer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: asynq-monitor
    ports:
      - "8181:8080"
    depends_on:
      - redis
volumes:
  redis_data:
