// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"vultisigner/ent/ecdsalocaldata"
	"vultisigner/ent/predicate"
	"vultisigner/ent/vault"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EcdsaLocalDataQuery is the builder for querying EcdsaLocalData entities.
type EcdsaLocalDataQuery struct {
	config
	ctx        *QueryContext
	order      []ecdsalocaldata.OrderOption
	inters     []Interceptor
	predicates []predicate.EcdsaLocalData
	withVault  *VaultQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EcdsaLocalDataQuery builder.
func (eldq *EcdsaLocalDataQuery) Where(ps ...predicate.EcdsaLocalData) *EcdsaLocalDataQuery {
	eldq.predicates = append(eldq.predicates, ps...)
	return eldq
}

// Limit the number of records to be returned by this query.
func (eldq *EcdsaLocalDataQuery) Limit(limit int) *EcdsaLocalDataQuery {
	eldq.ctx.Limit = &limit
	return eldq
}

// Offset to start from.
func (eldq *EcdsaLocalDataQuery) Offset(offset int) *EcdsaLocalDataQuery {
	eldq.ctx.Offset = &offset
	return eldq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eldq *EcdsaLocalDataQuery) Unique(unique bool) *EcdsaLocalDataQuery {
	eldq.ctx.Unique = &unique
	return eldq
}

// Order specifies how the records should be ordered.
func (eldq *EcdsaLocalDataQuery) Order(o ...ecdsalocaldata.OrderOption) *EcdsaLocalDataQuery {
	eldq.order = append(eldq.order, o...)
	return eldq
}

// QueryVault chains the current query on the "vault" edge.
func (eldq *EcdsaLocalDataQuery) QueryVault() *VaultQuery {
	query := (&VaultClient{config: eldq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eldq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eldq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ecdsalocaldata.Table, ecdsalocaldata.FieldID, selector),
			sqlgraph.To(vault.Table, vault.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ecdsalocaldata.VaultTable, ecdsalocaldata.VaultColumn),
		)
		fromU = sqlgraph.SetNeighbors(eldq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EcdsaLocalData entity from the query.
// Returns a *NotFoundError when no EcdsaLocalData was found.
func (eldq *EcdsaLocalDataQuery) First(ctx context.Context) (*EcdsaLocalData, error) {
	nodes, err := eldq.Limit(1).All(setContextOp(ctx, eldq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ecdsalocaldata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eldq *EcdsaLocalDataQuery) FirstX(ctx context.Context) *EcdsaLocalData {
	node, err := eldq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EcdsaLocalData ID from the query.
// Returns a *NotFoundError when no EcdsaLocalData ID was found.
func (eldq *EcdsaLocalDataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eldq.Limit(1).IDs(setContextOp(ctx, eldq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ecdsalocaldata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eldq *EcdsaLocalDataQuery) FirstIDX(ctx context.Context) int {
	id, err := eldq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EcdsaLocalData entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EcdsaLocalData entity is found.
// Returns a *NotFoundError when no EcdsaLocalData entities are found.
func (eldq *EcdsaLocalDataQuery) Only(ctx context.Context) (*EcdsaLocalData, error) {
	nodes, err := eldq.Limit(2).All(setContextOp(ctx, eldq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ecdsalocaldata.Label}
	default:
		return nil, &NotSingularError{ecdsalocaldata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eldq *EcdsaLocalDataQuery) OnlyX(ctx context.Context) *EcdsaLocalData {
	node, err := eldq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EcdsaLocalData ID in the query.
// Returns a *NotSingularError when more than one EcdsaLocalData ID is found.
// Returns a *NotFoundError when no entities are found.
func (eldq *EcdsaLocalDataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eldq.Limit(2).IDs(setContextOp(ctx, eldq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ecdsalocaldata.Label}
	default:
		err = &NotSingularError{ecdsalocaldata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eldq *EcdsaLocalDataQuery) OnlyIDX(ctx context.Context) int {
	id, err := eldq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EcdsaLocalDataSlice.
func (eldq *EcdsaLocalDataQuery) All(ctx context.Context) ([]*EcdsaLocalData, error) {
	ctx = setContextOp(ctx, eldq.ctx, "All")
	if err := eldq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EcdsaLocalData, *EcdsaLocalDataQuery]()
	return withInterceptors[[]*EcdsaLocalData](ctx, eldq, qr, eldq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eldq *EcdsaLocalDataQuery) AllX(ctx context.Context) []*EcdsaLocalData {
	nodes, err := eldq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EcdsaLocalData IDs.
func (eldq *EcdsaLocalDataQuery) IDs(ctx context.Context) (ids []int, err error) {
	if eldq.ctx.Unique == nil && eldq.path != nil {
		eldq.Unique(true)
	}
	ctx = setContextOp(ctx, eldq.ctx, "IDs")
	if err = eldq.Select(ecdsalocaldata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eldq *EcdsaLocalDataQuery) IDsX(ctx context.Context) []int {
	ids, err := eldq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eldq *EcdsaLocalDataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eldq.ctx, "Count")
	if err := eldq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eldq, querierCount[*EcdsaLocalDataQuery](), eldq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eldq *EcdsaLocalDataQuery) CountX(ctx context.Context) int {
	count, err := eldq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eldq *EcdsaLocalDataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eldq.ctx, "Exist")
	switch _, err := eldq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eldq *EcdsaLocalDataQuery) ExistX(ctx context.Context) bool {
	exist, err := eldq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EcdsaLocalDataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eldq *EcdsaLocalDataQuery) Clone() *EcdsaLocalDataQuery {
	if eldq == nil {
		return nil
	}
	return &EcdsaLocalDataQuery{
		config:     eldq.config,
		ctx:        eldq.ctx.Clone(),
		order:      append([]ecdsalocaldata.OrderOption{}, eldq.order...),
		inters:     append([]Interceptor{}, eldq.inters...),
		predicates: append([]predicate.EcdsaLocalData{}, eldq.predicates...),
		withVault:  eldq.withVault.Clone(),
		// clone intermediate query.
		sql:  eldq.sql.Clone(),
		path: eldq.path,
	}
}

// WithVault tells the query-builder to eager-load the nodes that are connected to
// the "vault" edge. The optional arguments are used to configure the query builder of the edge.
func (eldq *EcdsaLocalDataQuery) WithVault(opts ...func(*VaultQuery)) *EcdsaLocalDataQuery {
	query := (&VaultClient{config: eldq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eldq.withVault = query
	return eldq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		NTildeI string `json:"n_tilde_i,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EcdsaLocalData.Query().
//		GroupBy(ecdsalocaldata.FieldNTildeI).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eldq *EcdsaLocalDataQuery) GroupBy(field string, fields ...string) *EcdsaLocalDataGroupBy {
	eldq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EcdsaLocalDataGroupBy{build: eldq}
	grbuild.flds = &eldq.ctx.Fields
	grbuild.label = ecdsalocaldata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		NTildeI string `json:"n_tilde_i,omitempty"`
//	}
//
//	client.EcdsaLocalData.Query().
//		Select(ecdsalocaldata.FieldNTildeI).
//		Scan(ctx, &v)
func (eldq *EcdsaLocalDataQuery) Select(fields ...string) *EcdsaLocalDataSelect {
	eldq.ctx.Fields = append(eldq.ctx.Fields, fields...)
	sbuild := &EcdsaLocalDataSelect{EcdsaLocalDataQuery: eldq}
	sbuild.label = ecdsalocaldata.Label
	sbuild.flds, sbuild.scan = &eldq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EcdsaLocalDataSelect configured with the given aggregations.
func (eldq *EcdsaLocalDataQuery) Aggregate(fns ...AggregateFunc) *EcdsaLocalDataSelect {
	return eldq.Select().Aggregate(fns...)
}

func (eldq *EcdsaLocalDataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eldq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eldq); err != nil {
				return err
			}
		}
	}
	for _, f := range eldq.ctx.Fields {
		if !ecdsalocaldata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eldq.path != nil {
		prev, err := eldq.path(ctx)
		if err != nil {
			return err
		}
		eldq.sql = prev
	}
	return nil
}

func (eldq *EcdsaLocalDataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EcdsaLocalData, error) {
	var (
		nodes       = []*EcdsaLocalData{}
		_spec       = eldq.querySpec()
		loadedTypes = [1]bool{
			eldq.withVault != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EcdsaLocalData).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EcdsaLocalData{config: eldq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eldq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := eldq.withVault; query != nil {
		if err := eldq.loadVault(ctx, query, nodes, nil,
			func(n *EcdsaLocalData, e *Vault) { n.Edges.Vault = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eldq *EcdsaLocalDataQuery) loadVault(ctx context.Context, query *VaultQuery, nodes []*EcdsaLocalData, init func(*EcdsaLocalData), assign func(*EcdsaLocalData, *Vault)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*EcdsaLocalData)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Vault(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ecdsalocaldata.VaultColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ecdsa_local_data_vault
		if fk == nil {
			return fmt.Errorf(`foreign-key "ecdsa_local_data_vault" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ecdsa_local_data_vault" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (eldq *EcdsaLocalDataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eldq.querySpec()
	_spec.Node.Columns = eldq.ctx.Fields
	if len(eldq.ctx.Fields) > 0 {
		_spec.Unique = eldq.ctx.Unique != nil && *eldq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eldq.driver, _spec)
}

func (eldq *EcdsaLocalDataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ecdsalocaldata.Table, ecdsalocaldata.Columns, sqlgraph.NewFieldSpec(ecdsalocaldata.FieldID, field.TypeInt))
	_spec.From = eldq.sql
	if unique := eldq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eldq.path != nil {
		_spec.Unique = true
	}
	if fields := eldq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ecdsalocaldata.FieldID)
		for i := range fields {
			if fields[i] != ecdsalocaldata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eldq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eldq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eldq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eldq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eldq *EcdsaLocalDataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eldq.driver.Dialect())
	t1 := builder.Table(ecdsalocaldata.Table)
	columns := eldq.ctx.Fields
	if len(columns) == 0 {
		columns = ecdsalocaldata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eldq.sql != nil {
		selector = eldq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eldq.ctx.Unique != nil && *eldq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eldq.predicates {
		p(selector)
	}
	for _, p := range eldq.order {
		p(selector)
	}
	if offset := eldq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eldq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EcdsaLocalDataGroupBy is the group-by builder for EcdsaLocalData entities.
type EcdsaLocalDataGroupBy struct {
	selector
	build *EcdsaLocalDataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eldgb *EcdsaLocalDataGroupBy) Aggregate(fns ...AggregateFunc) *EcdsaLocalDataGroupBy {
	eldgb.fns = append(eldgb.fns, fns...)
	return eldgb
}

// Scan applies the selector query and scans the result into the given value.
func (eldgb *EcdsaLocalDataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eldgb.build.ctx, "GroupBy")
	if err := eldgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EcdsaLocalDataQuery, *EcdsaLocalDataGroupBy](ctx, eldgb.build, eldgb, eldgb.build.inters, v)
}

func (eldgb *EcdsaLocalDataGroupBy) sqlScan(ctx context.Context, root *EcdsaLocalDataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eldgb.fns))
	for _, fn := range eldgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eldgb.flds)+len(eldgb.fns))
		for _, f := range *eldgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eldgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eldgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EcdsaLocalDataSelect is the builder for selecting fields of EcdsaLocalData entities.
type EcdsaLocalDataSelect struct {
	*EcdsaLocalDataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (elds *EcdsaLocalDataSelect) Aggregate(fns ...AggregateFunc) *EcdsaLocalDataSelect {
	elds.fns = append(elds.fns, fns...)
	return elds
}

// Scan applies the selector query and scans the result into the given value.
func (elds *EcdsaLocalDataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, elds.ctx, "Select")
	if err := elds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EcdsaLocalDataQuery, *EcdsaLocalDataSelect](ctx, elds.EcdsaLocalDataQuery, elds, elds.inters, v)
}

func (elds *EcdsaLocalDataSelect) sqlScan(ctx context.Context, root *EcdsaLocalDataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(elds.fns))
	for _, fn := range elds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*elds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := elds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
