// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"vultisigner/ent/eddsalocaldata"
	"vultisigner/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EddsaLocalDataDelete is the builder for deleting a EddsaLocalData entity.
type EddsaLocalDataDelete struct {
	config
	hooks    []Hook
	mutation *EddsaLocalDataMutation
}

// Where appends a list predicates to the EddsaLocalDataDelete builder.
func (eldd *EddsaLocalDataDelete) Where(ps ...predicate.EddsaLocalData) *EddsaLocalDataDelete {
	eldd.mutation.Where(ps...)
	return eldd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (eldd *EddsaLocalDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, eldd.sqlExec, eldd.mutation, eldd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (eldd *EddsaLocalDataDelete) ExecX(ctx context.Context) int {
	n, err := eldd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (eldd *EddsaLocalDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(eddsalocaldata.Table, sqlgraph.NewFieldSpec(eddsalocaldata.FieldID, field.TypeInt))
	if ps := eldd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, eldd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	eldd.mutation.done = true
	return affected, err
}

// EddsaLocalDataDeleteOne is the builder for deleting a single EddsaLocalData entity.
type EddsaLocalDataDeleteOne struct {
	eldd *EddsaLocalDataDelete
}

// Where appends a list predicates to the EddsaLocalDataDelete builder.
func (elddo *EddsaLocalDataDeleteOne) Where(ps ...predicate.EddsaLocalData) *EddsaLocalDataDeleteOne {
	elddo.eldd.mutation.Where(ps...)
	return elddo
}

// Exec executes the deletion query.
func (elddo *EddsaLocalDataDeleteOne) Exec(ctx context.Context) error {
	n, err := elddo.eldd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eddsalocaldata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (elddo *EddsaLocalDataDeleteOne) ExecX(ctx context.Context) {
	if err := elddo.Exec(ctx); err != nil {
		panic(err)
	}
}
