// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"vultisigner/ent/pailliersk"
	"vultisigner/ent/predicate"
	"vultisigner/ent/vault"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaillierSKQuery is the builder for querying PaillierSK entities.
type PaillierSKQuery struct {
	config
	ctx        *QueryContext
	order      []pailliersk.OrderOption
	inters     []Interceptor
	predicates []predicate.PaillierSK
	withVault  *VaultQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PaillierSKQuery builder.
func (psq *PaillierSKQuery) Where(ps ...predicate.PaillierSK) *PaillierSKQuery {
	psq.predicates = append(psq.predicates, ps...)
	return psq
}

// Limit the number of records to be returned by this query.
func (psq *PaillierSKQuery) Limit(limit int) *PaillierSKQuery {
	psq.ctx.Limit = &limit
	return psq
}

// Offset to start from.
func (psq *PaillierSKQuery) Offset(offset int) *PaillierSKQuery {
	psq.ctx.Offset = &offset
	return psq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (psq *PaillierSKQuery) Unique(unique bool) *PaillierSKQuery {
	psq.ctx.Unique = &unique
	return psq
}

// Order specifies how the records should be ordered.
func (psq *PaillierSKQuery) Order(o ...pailliersk.OrderOption) *PaillierSKQuery {
	psq.order = append(psq.order, o...)
	return psq
}

// QueryVault chains the current query on the "vault" edge.
func (psq *PaillierSKQuery) QueryVault() *VaultQuery {
	query := (&VaultClient{config: psq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := psq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := psq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pailliersk.Table, pailliersk.FieldID, selector),
			sqlgraph.To(vault.Table, vault.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, pailliersk.VaultTable, pailliersk.VaultColumn),
		)
		fromU = sqlgraph.SetNeighbors(psq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PaillierSK entity from the query.
// Returns a *NotFoundError when no PaillierSK was found.
func (psq *PaillierSKQuery) First(ctx context.Context) (*PaillierSK, error) {
	nodes, err := psq.Limit(1).All(setContextOp(ctx, psq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pailliersk.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (psq *PaillierSKQuery) FirstX(ctx context.Context) *PaillierSK {
	node, err := psq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PaillierSK ID from the query.
// Returns a *NotFoundError when no PaillierSK ID was found.
func (psq *PaillierSKQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = psq.Limit(1).IDs(setContextOp(ctx, psq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pailliersk.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (psq *PaillierSKQuery) FirstIDX(ctx context.Context) int {
	id, err := psq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PaillierSK entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PaillierSK entity is found.
// Returns a *NotFoundError when no PaillierSK entities are found.
func (psq *PaillierSKQuery) Only(ctx context.Context) (*PaillierSK, error) {
	nodes, err := psq.Limit(2).All(setContextOp(ctx, psq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pailliersk.Label}
	default:
		return nil, &NotSingularError{pailliersk.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (psq *PaillierSKQuery) OnlyX(ctx context.Context) *PaillierSK {
	node, err := psq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PaillierSK ID in the query.
// Returns a *NotSingularError when more than one PaillierSK ID is found.
// Returns a *NotFoundError when no entities are found.
func (psq *PaillierSKQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = psq.Limit(2).IDs(setContextOp(ctx, psq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pailliersk.Label}
	default:
		err = &NotSingularError{pailliersk.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (psq *PaillierSKQuery) OnlyIDX(ctx context.Context) int {
	id, err := psq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PaillierSKs.
func (psq *PaillierSKQuery) All(ctx context.Context) ([]*PaillierSK, error) {
	ctx = setContextOp(ctx, psq.ctx, "All")
	if err := psq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PaillierSK, *PaillierSKQuery]()
	return withInterceptors[[]*PaillierSK](ctx, psq, qr, psq.inters)
}

// AllX is like All, but panics if an error occurs.
func (psq *PaillierSKQuery) AllX(ctx context.Context) []*PaillierSK {
	nodes, err := psq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PaillierSK IDs.
func (psq *PaillierSKQuery) IDs(ctx context.Context) (ids []int, err error) {
	if psq.ctx.Unique == nil && psq.path != nil {
		psq.Unique(true)
	}
	ctx = setContextOp(ctx, psq.ctx, "IDs")
	if err = psq.Select(pailliersk.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (psq *PaillierSKQuery) IDsX(ctx context.Context) []int {
	ids, err := psq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (psq *PaillierSKQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, psq.ctx, "Count")
	if err := psq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, psq, querierCount[*PaillierSKQuery](), psq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (psq *PaillierSKQuery) CountX(ctx context.Context) int {
	count, err := psq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (psq *PaillierSKQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, psq.ctx, "Exist")
	switch _, err := psq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (psq *PaillierSKQuery) ExistX(ctx context.Context) bool {
	exist, err := psq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PaillierSKQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (psq *PaillierSKQuery) Clone() *PaillierSKQuery {
	if psq == nil {
		return nil
	}
	return &PaillierSKQuery{
		config:     psq.config,
		ctx:        psq.ctx.Clone(),
		order:      append([]pailliersk.OrderOption{}, psq.order...),
		inters:     append([]Interceptor{}, psq.inters...),
		predicates: append([]predicate.PaillierSK{}, psq.predicates...),
		withVault:  psq.withVault.Clone(),
		// clone intermediate query.
		sql:  psq.sql.Clone(),
		path: psq.path,
	}
}

// WithVault tells the query-builder to eager-load the nodes that are connected to
// the "vault" edge. The optional arguments are used to configure the query builder of the edge.
func (psq *PaillierSKQuery) WithVault(opts ...func(*VaultQuery)) *PaillierSKQuery {
	query := (&VaultClient{config: psq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	psq.withVault = query
	return psq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		N string `json:"n,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PaillierSK.Query().
//		GroupBy(pailliersk.FieldN).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (psq *PaillierSKQuery) GroupBy(field string, fields ...string) *PaillierSKGroupBy {
	psq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PaillierSKGroupBy{build: psq}
	grbuild.flds = &psq.ctx.Fields
	grbuild.label = pailliersk.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		N string `json:"n,omitempty"`
//	}
//
//	client.PaillierSK.Query().
//		Select(pailliersk.FieldN).
//		Scan(ctx, &v)
func (psq *PaillierSKQuery) Select(fields ...string) *PaillierSKSelect {
	psq.ctx.Fields = append(psq.ctx.Fields, fields...)
	sbuild := &PaillierSKSelect{PaillierSKQuery: psq}
	sbuild.label = pailliersk.Label
	sbuild.flds, sbuild.scan = &psq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PaillierSKSelect configured with the given aggregations.
func (psq *PaillierSKQuery) Aggregate(fns ...AggregateFunc) *PaillierSKSelect {
	return psq.Select().Aggregate(fns...)
}

func (psq *PaillierSKQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range psq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, psq); err != nil {
				return err
			}
		}
	}
	for _, f := range psq.ctx.Fields {
		if !pailliersk.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if psq.path != nil {
		prev, err := psq.path(ctx)
		if err != nil {
			return err
		}
		psq.sql = prev
	}
	return nil
}

func (psq *PaillierSKQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PaillierSK, error) {
	var (
		nodes       = []*PaillierSK{}
		_spec       = psq.querySpec()
		loadedTypes = [1]bool{
			psq.withVault != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PaillierSK).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PaillierSK{config: psq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, psq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := psq.withVault; query != nil {
		if err := psq.loadVault(ctx, query, nodes, nil,
			func(n *PaillierSK, e *Vault) { n.Edges.Vault = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (psq *PaillierSKQuery) loadVault(ctx context.Context, query *VaultQuery, nodes []*PaillierSK, init func(*PaillierSK), assign func(*PaillierSK, *Vault)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PaillierSK)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Vault(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(pailliersk.VaultColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.paillier_sk_vault
		if fk == nil {
			return fmt.Errorf(`foreign-key "paillier_sk_vault" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "paillier_sk_vault" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (psq *PaillierSKQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := psq.querySpec()
	_spec.Node.Columns = psq.ctx.Fields
	if len(psq.ctx.Fields) > 0 {
		_spec.Unique = psq.ctx.Unique != nil && *psq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, psq.driver, _spec)
}

func (psq *PaillierSKQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pailliersk.Table, pailliersk.Columns, sqlgraph.NewFieldSpec(pailliersk.FieldID, field.TypeInt))
	_spec.From = psq.sql
	if unique := psq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if psq.path != nil {
		_spec.Unique = true
	}
	if fields := psq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pailliersk.FieldID)
		for i := range fields {
			if fields[i] != pailliersk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := psq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := psq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := psq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := psq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (psq *PaillierSKQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(psq.driver.Dialect())
	t1 := builder.Table(pailliersk.Table)
	columns := psq.ctx.Fields
	if len(columns) == 0 {
		columns = pailliersk.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if psq.sql != nil {
		selector = psq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if psq.ctx.Unique != nil && *psq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range psq.predicates {
		p(selector)
	}
	for _, p := range psq.order {
		p(selector)
	}
	if offset := psq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := psq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PaillierSKGroupBy is the group-by builder for PaillierSK entities.
type PaillierSKGroupBy struct {
	selector
	build *PaillierSKQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (psgb *PaillierSKGroupBy) Aggregate(fns ...AggregateFunc) *PaillierSKGroupBy {
	psgb.fns = append(psgb.fns, fns...)
	return psgb
}

// Scan applies the selector query and scans the result into the given value.
func (psgb *PaillierSKGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, psgb.build.ctx, "GroupBy")
	if err := psgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaillierSKQuery, *PaillierSKGroupBy](ctx, psgb.build, psgb, psgb.build.inters, v)
}

func (psgb *PaillierSKGroupBy) sqlScan(ctx context.Context, root *PaillierSKQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(psgb.fns))
	for _, fn := range psgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*psgb.flds)+len(psgb.fns))
		for _, f := range *psgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*psgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := psgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PaillierSKSelect is the builder for selecting fields of PaillierSK entities.
type PaillierSKSelect struct {
	*PaillierSKQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pss *PaillierSKSelect) Aggregate(fns ...AggregateFunc) *PaillierSKSelect {
	pss.fns = append(pss.fns, fns...)
	return pss
}

// Scan applies the selector query and scans the result into the given value.
func (pss *PaillierSKSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pss.ctx, "Select")
	if err := pss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaillierSKQuery, *PaillierSKSelect](ctx, pss.PaillierSKQuery, pss, pss.inters, v)
}

func (pss *PaillierSKSelect) sqlScan(ctx context.Context, root *PaillierSKQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pss.fns))
	for _, fn := range pss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
