// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"vultisigner/ent/pailliersk"
	"vultisigner/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaillierSKDelete is the builder for deleting a PaillierSK entity.
type PaillierSKDelete struct {
	config
	hooks    []Hook
	mutation *PaillierSKMutation
}

// Where appends a list predicates to the PaillierSKDelete builder.
func (psd *PaillierSKDelete) Where(ps ...predicate.PaillierSK) *PaillierSKDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *PaillierSKDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *PaillierSKDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *PaillierSKDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pailliersk.Table, sqlgraph.NewFieldSpec(pailliersk.FieldID, field.TypeInt))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// PaillierSKDeleteOne is the builder for deleting a single PaillierSK entity.
type PaillierSKDeleteOne struct {
	psd *PaillierSKDelete
}

// Where appends a list predicates to the PaillierSKDelete builder.
func (psdo *PaillierSKDeleteOne) Where(ps ...predicate.PaillierSK) *PaillierSKDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *PaillierSKDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pailliersk.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *PaillierSKDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
