// SPDX-License-Identifier: Apache-2.0
//
// Copyright © 2017 Trust Wallet.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: Everscale.proto

package everscale

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message option
type MessageBehavior int32

const (
	// Sends a message with the specified amount. The sender pays a fee from the account balance
	MessageBehavior_SimpleTransfer MessageBehavior = 0
	// Sends the entire account balance along with the message
	MessageBehavior_SendAllBalance MessageBehavior = 1
)

// Enum value maps for MessageBehavior.
var (
	MessageBehavior_name = map[int32]string{
		0: "SimpleTransfer",
		1: "SendAllBalance",
	}
	MessageBehavior_value = map[string]int32{
		"SimpleTransfer": 0,
		"SendAllBalance": 1,
	}
)

func (x MessageBehavior) Enum() *MessageBehavior {
	p := new(MessageBehavior)
	*p = x
	return p
}

func (x MessageBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_Everscale_proto_enumTypes[0].Descriptor()
}

func (MessageBehavior) Type() protoreflect.EnumType {
	return &file_Everscale_proto_enumTypes[0]
}

func (x MessageBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageBehavior.Descriptor instead.
func (MessageBehavior) EnumDescriptor() ([]byte, []int) {
	return file_Everscale_proto_rawDescGZIP(), []int{0}
}

// Transfer message
type Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If set to true, then the message will be returned if there is an error on the recipient's side.
	Bounce bool `protobuf:"varint,1,opt,name=bounce,proto3" json:"bounce,omitempty"`
	// Affect the attached amount and fees
	Behavior MessageBehavior `protobuf:"varint,2,opt,name=behavior,proto3,enum=TW.Everscale.Proto.MessageBehavior" json:"behavior,omitempty"`
	// Amount to send in nano EVER
	Amount uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Expiration UNIX timestamp
	ExpiredAt uint32 `protobuf:"varint,4,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	// Recipient address
	To string `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	// Account state if there is any
	//
	// Types that are assignable to AccountStateOneof:
	//
	//	*Transfer_EncodedContractData
	AccountStateOneof isTransfer_AccountStateOneof `protobuf_oneof:"account_state_oneof"`
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Everscale_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_Everscale_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_Everscale_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetBounce() bool {
	if x != nil {
		return x.Bounce
	}
	return false
}

func (x *Transfer) GetBehavior() MessageBehavior {
	if x != nil {
		return x.Behavior
	}
	return MessageBehavior_SimpleTransfer
}

func (x *Transfer) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetExpiredAt() uint32 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *Transfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (m *Transfer) GetAccountStateOneof() isTransfer_AccountStateOneof {
	if m != nil {
		return m.AccountStateOneof
	}
	return nil
}

func (x *Transfer) GetEncodedContractData() string {
	if x, ok := x.GetAccountStateOneof().(*Transfer_EncodedContractData); ok {
		return x.EncodedContractData
	}
	return ""
}

type isTransfer_AccountStateOneof interface {
	isTransfer_AccountStateOneof()
}

type Transfer_EncodedContractData struct {
	// Just contract data
	EncodedContractData string `protobuf:"bytes,6,opt,name=encoded_contract_data,json=encodedContractData,proto3,oneof"`
}

func (*Transfer_EncodedContractData) isTransfer_AccountStateOneof() {}

// Input data necessary to create a signed transaction.
type SigningInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The payload transfer
	//
	// Types that are assignable to ActionOneof:
	//
	//	*SigningInput_Transfer
	ActionOneof isSigningInput_ActionOneof `protobuf_oneof:"action_oneof"`
	// The secret private key used for signing (32 bytes).
	PrivateKey []byte `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Everscale_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_Everscale_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_Everscale_proto_rawDescGZIP(), []int{1}
}

func (m *SigningInput) GetActionOneof() isSigningInput_ActionOneof {
	if m != nil {
		return m.ActionOneof
	}
	return nil
}

func (x *SigningInput) GetTransfer() *Transfer {
	if x, ok := x.GetActionOneof().(*SigningInput_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (x *SigningInput) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type isSigningInput_ActionOneof interface {
	isSigningInput_ActionOneof()
}

type SigningInput_Transfer struct {
	Transfer *Transfer `protobuf:"bytes,1,opt,name=transfer,proto3,oneof"`
}

func (*SigningInput_Transfer) isSigningInput_ActionOneof() {}

// Result containing the signed and encoded transaction.
type SigningOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encoded string `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Everscale_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_Everscale_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_Everscale_proto_rawDescGZIP(), []int{2}
}

func (x *SigningOutput) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

var File_Everscale_proto protoreflect.FileDescriptor

var file_Everscale_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x45, 0x76, 0x65, 0x72, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x54, 0x57, 0x2e, 0x45, 0x76, 0x65, 0x72, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x01, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x62, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x54,
	0x57, 0x2e, 0x45, 0x76, 0x65, 0x72, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f,
	0x72, 0x52, 0x08, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x34, 0x0a, 0x15, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x13, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x42, 0x15, 0x0a, 0x13, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22,
	0x7b, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x3a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x54, 0x57, 0x2e, 0x45, 0x76, 0x65, 0x72, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x42, 0x0e, 0x0a, 0x0c,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x29, 0x0a, 0x0d,
	0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x2a, 0x39, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x10, 0x01, 0x42, 0x17, 0x0a, 0x15, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x6a, 0x6e, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Everscale_proto_rawDescOnce sync.Once
	file_Everscale_proto_rawDescData = file_Everscale_proto_rawDesc
)

func file_Everscale_proto_rawDescGZIP() []byte {
	file_Everscale_proto_rawDescOnce.Do(func() {
		file_Everscale_proto_rawDescData = protoimpl.X.CompressGZIP(file_Everscale_proto_rawDescData)
	})
	return file_Everscale_proto_rawDescData
}

var file_Everscale_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Everscale_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Everscale_proto_goTypes = []interface{}{
	(MessageBehavior)(0),  // 0: TW.Everscale.Proto.MessageBehavior
	(*Transfer)(nil),      // 1: TW.Everscale.Proto.Transfer
	(*SigningInput)(nil),  // 2: TW.Everscale.Proto.SigningInput
	(*SigningOutput)(nil), // 3: TW.Everscale.Proto.SigningOutput
}
var file_Everscale_proto_depIdxs = []int32{
	0, // 0: TW.Everscale.Proto.Transfer.behavior:type_name -> TW.Everscale.Proto.MessageBehavior
	1, // 1: TW.Everscale.Proto.SigningInput.transfer:type_name -> TW.Everscale.Proto.Transfer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Everscale_proto_init() }
func file_Everscale_proto_init() {
	if File_Everscale_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Everscale_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Everscale_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Everscale_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Everscale_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Transfer_EncodedContractData)(nil),
	}
	file_Everscale_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SigningInput_Transfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Everscale_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Everscale_proto_goTypes,
		DependencyIndexes: file_Everscale_proto_depIdxs,
		EnumInfos:         file_Everscale_proto_enumTypes,
		MessageInfos:      file_Everscale_proto_msgTypes,
	}.Build()
	File_Everscale_proto = out.File
	file_Everscale_proto_rawDesc = nil
	file_Everscale_proto_goTypes = nil
	file_Everscale_proto_depIdxs = nil
}
